### ISSUE TITLE
flexbox_rb en rails 5.1.1

### ISSUE THREAD

**Issue by jeisonarenales** [urielhdz/flexbox_rb#5]
Hola Uriel, tengo el siguiente problema. tengo instalada la version de flexbox_rb 0.2.7.1 y la version de rails 5.1.1. Me da un error al usar la librería. Me puedes ayudar con eso. Gracias Estoy siguiendo el curso de Rails de codigofacilito.

**Comment by josera21** [comment]
Tengo el mismo problema que @jeison24 en Rails 5.1.2

**Comment by josera21** [comment]
Lo solucione agregando la gem en el gemfile sin especificar la version a usar, solo:

gem 'flexbox_rb'
