### ISSUE TITLE
Uso de Offsets

### ISSUE THREAD

**Issue by davidlares** [urielhdz/flexbox_rb#6]
Posiblemente exista una forma en la que se puedan implementar los offsets en los div dentro de FlexBox implementando esta gema, pero no doy con el resultado correcto.

El codigo HTML correcto, debería ser: `<div class="col-lg-offset-5"> ...`

Al implementarlo vía flexbox_url, genera errores:

  `=grid lg-offset:5 do ... `

El error es generado por error de sintaxis, además de que el IDE (cualquiera que soporte Ruby Haml) no reconoce o colorea el "-offset" como correcto. ¿Alguna solución para el caso particular?

**Comment by urielhdz** [comment]
Hola david, debería ser algo así

```haml
=grid class:"lg-offset-5" do
```

Saludos

**Comment by davidlares** [comment]
Gracias, @urielhdz.
